name: Create private infrastructure in Azure

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: 
      name: CSS
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./storagedeployment.bicep
        failOnStdErr: false

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./private.bicep
        failOnStdErr: false